/** Static development seed data. Prices are integer minor units (pence). */

export const BRANCHES = [
  {
    name: 'HQ Distribution Centre',
    code: 'HQ',
    slug: 'hq',
    addressLine1: '1 Commerce Way',
    city: 'Glasgow',
    postcode: 'G1 1AA',
    country: 'GB',
    phone: '+44 141 000 0000',
    email: 'hq@dev.local',
    latitude: 55.861,
    longitude: -4.25,
    deliveryEnabled: false,
    clickCollectEnabled: false,
    deliveryFee: 0,
  },
  {
    name: 'Glasgow Central',
    code: 'GLA',
    slug: 'glasgow',
    addressLine1: '12 Buchanan Street',
    city: 'Glasgow',
    postcode: 'G1 3BA',
    country: 'GB',
    phone: '+44 141 111 1111',
    email: 'glasgow@dev.local',
    latitude: 55.8609,
    longitude: -4.2521,
    deliveryFee: 399,
    freeDeliveryThreshold: 3000,
  },
  {
    name: 'Edinburgh Princes Street',
    code: 'EDI',
    slug: 'edinburgh',
    addressLine1: '88 Princes Street',
    city: 'Edinburgh',
    postcode: 'EH2 2ER',
    country: 'GB',
    phone: '+44 131 222 2222',
    email: 'edinburgh@dev.local',
    latitude: 55.952,
    longitude: -3.1957,
    deliveryFee: 449,
    freeDeliveryThreshold: 3500,
  },
  {
    name: 'Paisley High Street',
    code: 'PAI',
    slug: 'paisley',
    addressLine1: '5 High Street',
    city: 'Paisley',
    postcode: 'PA1 2AF',
    country: 'GB',
    phone: '+44 141 333 3333',
    email: 'paisley@dev.local',
    latitude: 55.8455,
    longitude: -4.4237,
    deliveryFee: 349,
    freeDeliveryThreshold: 2500,
  },
  {
    name: 'Manchester Arndale',
    code: 'MAN',
    slug: 'manchester',
    addressLine1: '49 Market Street',
    city: 'Manchester',
    postcode: 'M1 1WR',
    country: 'GB',
    phone: '+44 161 444 4444',
    email: 'manchester@dev.local',
    latitude: 53.484,
    longitude: -2.2413,
    deliveryFee: 399,
    freeDeliveryThreshold: 3000,
  },
  {
    name: 'London Oxford Street',
    code: 'LON',
    slug: 'london',
    addressLine1: '200 Oxford Street',
    city: 'London',
    postcode: 'W1D 1NU',
    country: 'GB',
    phone: '+44 20 5555 5555',
    email: 'london@dev.local',
    latitude: 51.5154,
    longitude: -0.1411,
    deliveryFee: 499,
    freeDeliveryThreshold: 4000,
  },
];

export const CATEGORIES = [
  { name: 'Energy Drinks', slug: 'energy-drinks', sortOrder: 1 },
  { name: 'Soft Drinks', slug: 'soft-drinks', sortOrder: 2 },
  { name: 'Water & Juice', slug: 'water-juice', sortOrder: 3 },
  { name: 'Crisps & Snacks', slug: 'crisps-snacks', sortOrder: 4 },
  { name: 'Confectionery', slug: 'confectionery', sortOrder: 5 },
  { name: 'Biscuits & Cakes', slug: 'biscuits-cakes', sortOrder: 6 },
  { name: 'Household', slug: 'household', sortOrder: 7 },
  { name: 'Health & Beauty', slug: 'health-beauty', sortOrder: 8 },
];

export interface SeedVariant {
  suffix: string;
  name: string;
  attributes: Record<string, string>;
  priceDelta?: number;
  isDefault?: boolean;
}

export interface SeedProduct {
  sku: string;
  barcode?: string;
  name: string;
  slug: string;
  shortDescription: string;
  description?: string;
  brand: string;
  basePrice: number;
  taxClass?: 'STANDARD' | 'REDUCED' | 'ZERO';
  images: string[];
  tags: string[];
  categorySlugs: string[];
  variants: SeedVariant[];
}

/** Stable demo imagery — primary + secondary angles per product. */
const img = (seed: string, second = false) =>
  `https://picsum.photos/seed/${encodeURIComponent(seed)}${second ? '-b' : ''}/800/800`;

const gallery = (seed: string) => [img(seed), img(seed, true)];

export const PRODUCTS: SeedProduct[] = [
  {
    sku: 'MON-ORIG-500',
    barcode: '5060166690034',
    name: 'Monster Energy Original 500ml',
    slug: 'monster-energy-original-500ml',
    shortDescription: 'The original green Monster Energy drink, 500ml can.',
    description: 'Monster Energy Original delivers a powerful punch with its classic blend. 500ml can.',
    brand: 'Monster',
    basePrice: 149,
    images: gallery('Monster Original'),
    tags: ['energy', 'drinks', 'monster'],
    categorySlugs: ['energy-drinks'],
    variants: [],
  },
  {
    sku: 'MON-ULTRA-500',
    barcode: '5060337500401',
    name: 'Monster Energy Ultra 500ml',
    slug: 'monster-energy-ultra-500ml',
    shortDescription: 'Zero sugar sparkling energy drink, 500ml can.',
    brand: 'Monster',
    basePrice: 155,
    images: gallery('Monster Ultra'),
    tags: ['energy', 'zero-sugar'],
    categorySlugs: ['energy-drinks'],
    variants: [
      { suffix: 'WHT', name: 'Monster Ultra White 500ml', attributes: { flavour: 'White' }, isDefault: true },
      { suffix: 'PAR', name: 'Monster Ultra Paradise 500ml', attributes: { flavour: 'Paradise' } },
      { suffix: 'GLD', name: 'Monster Ultra Gold 500ml', attributes: { flavour: 'Gold' }, priceDelta: 10 },
    ],
  },
  {
    sku: 'RB-ORIG-250',
    barcode: '9002490100070',
    name: 'Red Bull Energy Drink 250ml',
    slug: 'red-bull-energy-drink-250ml',
    shortDescription: 'Red Bull gives you wings. 250ml can.',
    brand: 'Red Bull',
    basePrice: 135,
    images: gallery('Red Bull'),
    tags: ['energy'],
    categorySlugs: ['energy-drinks'],
    variants: [],
  },
  {
    sku: 'RB-SF-250',
    name: 'Red Bull Sugarfree 250ml',
    slug: 'red-bull-sugarfree-250ml',
    shortDescription: 'Red Bull Sugarfree, all the wings without the sugar.',
    brand: 'Red Bull',
    basePrice: 135,
    images: gallery('Red Bull SF'),
    tags: ['energy', 'zero-sugar'],
    categorySlugs: ['energy-drinks'],
    variants: [],
  },
  {
    sku: 'COKE-330',
    barcode: '5449000000996',
    name: 'Coca-Cola Original 330ml',
    slug: 'coca-cola-original-330ml',
    shortDescription: 'Classic Coca-Cola taste, 330ml can.',
    brand: 'Coca-Cola',
    basePrice: 90,
    images: gallery('Coca-Cola'),
    tags: ['soft-drink', 'cola'],
    categorySlugs: ['soft-drinks'],
    variants: [],
  },
  {
    sku: 'COKE-ZERO-330',
    name: 'Coca-Cola Zero Sugar 330ml',
    slug: 'coca-cola-zero-sugar-330ml',
    shortDescription: 'Zero sugar, all the taste. 330ml can.',
    brand: 'Coca-Cola',
    basePrice: 90,
    images: gallery('Coke Zero'),
    tags: ['soft-drink', 'zero-sugar'],
    categorySlugs: ['soft-drinks'],
    variants: [],
  },
  {
    sku: 'FANTA-330',
    name: 'Fanta Orange 330ml',
    slug: 'fanta-orange-330ml',
    shortDescription: 'Bubbly orange refreshment, 330ml can.',
    brand: 'Fanta',
    basePrice: 85,
    images: gallery('Fanta'),
    tags: ['soft-drink'],
    categorySlugs: ['soft-drinks'],
    variants: [],
  },
  {
    sku: 'SPRITE-330',
    name: 'Sprite Lemon-Lime 330ml',
    slug: 'sprite-lemon-lime-330ml',
    shortDescription: 'Crisp lemon-lime soda, 330ml can.',
    brand: 'Sprite',
    basePrice: 85,
    images: gallery('Sprite'),
    tags: ['soft-drink'],
    categorySlugs: ['soft-drinks'],
    variants: [],
  },
  {
    sku: 'IRNBRU-330',
    barcode: '5000382000403',
    name: 'Irn-Bru 330ml',
    slug: 'irn-bru-330ml',
    shortDescription: "Scotland's other national drink, 330ml can.",
    brand: 'Irn-Bru',
    basePrice: 89,
    images: gallery('Irn-Bru'),
    tags: ['soft-drink', 'scottish'],
    categorySlugs: ['soft-drinks'],
    variants: [],
  },
  {
    sku: 'PEPSI-MAX-330',
    name: 'Pepsi Max 330ml',
    slug: 'pepsi-max-330ml',
    shortDescription: 'Maximum taste, no sugar. 330ml can.',
    brand: 'Pepsi',
    basePrice: 85,
    images: gallery('Pepsi Max'),
    tags: ['soft-drink', 'zero-sugar'],
    categorySlugs: ['soft-drinks'],
    variants: [],
  },
  {
    sku: 'EVIAN-500',
    name: 'Evian Natural Mineral Water 500ml',
    slug: 'evian-water-500ml',
    shortDescription: 'Natural mineral water from the French Alps.',
    brand: 'Evian',
    basePrice: 110,
    taxClass: 'ZERO',
    images: gallery('Evian'),
    tags: ['water'],
    categorySlugs: ['water-juice'],
    variants: [],
  },
  {
    sku: 'TROP-OJ-1L',
    name: 'Tropicana Orange Juice 1L',
    slug: 'tropicana-orange-juice-1l',
    shortDescription: 'Smooth orange juice, not from concentrate.',
    brand: 'Tropicana',
    basePrice: 250,
    taxClass: 'ZERO',
    images: gallery('Tropicana'),
    tags: ['juice'],
    categorySlugs: ['water-juice'],
    variants: [],
  },
  {
    sku: 'WALK-CHS-32',
    barcode: '5000328356303',
    name: 'Walkers Cheese & Onion 32.5g',
    slug: 'walkers-cheese-onion-32g',
    shortDescription: 'Classic cheese and onion crisps.',
    brand: 'Walkers',
    basePrice: 85,
    images: gallery('Walkers C&O'),
    tags: ['crisps'],
    categorySlugs: ['crisps-snacks'],
    variants: [],
  },
  {
    sku: 'WALK-RS-32',
    name: 'Walkers Ready Salted 32.5g',
    slug: 'walkers-ready-salted-32g',
    shortDescription: 'Classic ready salted crisps.',
    brand: 'Walkers',
    basePrice: 85,
    images: gallery('Walkers RS'),
    tags: ['crisps'],
    categorySlugs: ['crisps-snacks'],
    variants: [],
  },
  {
    sku: 'DORITO-CHILL-150',
    name: 'Doritos Chilli Heatwave 150g',
    slug: 'doritos-chilli-heatwave-150g',
    shortDescription: 'Bold chilli heatwave tortilla chips, sharing bag.',
    brand: 'Doritos',
    basePrice: 225,
    images: gallery('Doritos'),
    tags: ['crisps', 'sharing'],
    categorySlugs: ['crisps-snacks'],
    variants: [],
  },
  {
    sku: 'PRINGLES-ORIG-165',
    name: 'Pringles Original 165g',
    slug: 'pringles-original-165g',
    shortDescription: 'Once you pop, you can’t stop.',
    brand: 'Pringles',
    basePrice: 265,
    images: gallery('Pringles'),
    tags: ['crisps', 'sharing'],
    categorySlugs: ['crisps-snacks'],
    variants: [
      { suffix: 'ORIG', name: 'Pringles Original 165g', attributes: { flavour: 'Original' }, isDefault: true },
      { suffix: 'SRCM', name: 'Pringles Sour Cream & Onion 165g', attributes: { flavour: 'Sour Cream & Onion' } },
      { suffix: 'BBQ', name: 'Pringles Texas BBQ 165g', attributes: { flavour: 'Texas BBQ' } },
    ],
  },
  {
    sku: 'CADB-DM-110',
    barcode: '7622210989741',
    name: 'Cadbury Dairy Milk 110g',
    slug: 'cadbury-dairy-milk-110g',
    shortDescription: 'A glass and a half of milk chocolate.',
    brand: 'Cadbury',
    basePrice: 200,
    images: gallery('Dairy Milk'),
    tags: ['chocolate'],
    categorySlugs: ['confectionery'],
    variants: [],
  },
  {
    sku: 'CADB-TWIRL',
    name: 'Cadbury Twirl',
    slug: 'cadbury-twirl',
    shortDescription: 'Swirls of Cadbury chocolate in a crumbly flake.',
    brand: 'Cadbury',
    basePrice: 85,
    images: gallery('Twirl'),
    tags: ['chocolate'],
    categorySlugs: ['confectionery'],
    variants: [],
  },
  {
    sku: 'HARIBO-STAR-160',
    name: 'Haribo Starmix 160g',
    slug: 'haribo-starmix-160g',
    shortDescription: 'Kids and grown-ups love it so.',
    brand: 'Haribo',
    basePrice: 135,
    images: gallery('Haribo'),
    tags: ['sweets'],
    categorySlugs: ['confectionery'],
    variants: [],
  },
  {
    sku: 'SKITTLES-136',
    name: 'Skittles Fruits 136g',
    slug: 'skittles-fruits-136g',
    shortDescription: 'Taste the rainbow.',
    brand: 'Skittles',
    basePrice: 125,
    images: gallery('Skittles'),
    tags: ['sweets'],
    categorySlugs: ['confectionery'],
    variants: [],
  },
  {
    sku: 'MCVIT-DIG-400',
    name: 'McVitie’s Digestives 400g',
    slug: 'mcvities-digestives-400g',
    shortDescription: 'The nation’s favourite biscuit.',
    brand: 'McVitie’s',
    basePrice: 180,
    taxClass: 'ZERO',
    images: gallery('Digestives'),
    tags: ['biscuits'],
    categorySlugs: ['biscuits-cakes'],
    variants: [
      { suffix: 'PLN', name: 'McVitie’s Digestives 400g', attributes: { type: 'Plain' }, isDefault: true },
      { suffix: 'MLK', name: 'McVitie’s Milk Chocolate Digestives 316g', attributes: { type: 'Milk Chocolate' }, priceDelta: 40 },
      { suffix: 'DRK', name: 'McVitie’s Dark Chocolate Digestives 316g', attributes: { type: 'Dark Chocolate' }, priceDelta: 40 },
    ],
  },
  {
    sku: 'OREO-154',
    name: 'Oreo Original 154g',
    slug: 'oreo-original-154g',
    shortDescription: 'Twist, lick, dunk.',
    brand: 'Oreo',
    basePrice: 120,
    taxClass: 'ZERO',
    images: gallery('Oreo'),
    tags: ['biscuits'],
    categorySlugs: ['biscuits-cakes'],
    variants: [],
  },
  {
    sku: 'FAIRY-ORIG-433',
    name: 'Fairy Original Washing Up Liquid 433ml',
    slug: 'fairy-original-433ml',
    shortDescription: 'Trusted sparkling clean dishes.',
    brand: 'Fairy',
    basePrice: 175,
    images: gallery('Fairy'),
    tags: ['household', 'cleaning'],
    categorySlugs: ['household'],
    variants: [],
  },
  {
    sku: 'ANDREX-4PK',
    name: 'Andrex Classic Clean Toilet Roll 4 Pack',
    slug: 'andrex-classic-4-pack',
    shortDescription: 'Soft, strong toilet tissue.',
    brand: 'Andrex',
    basePrice: 285,
    taxClass: 'REDUCED',
    images: gallery('Andrex'),
    tags: ['household'],
    categorySlugs: ['household'],
    variants: [],
  },
  {
    sku: 'FLASH-SPRAY-500',
    name: 'Flash Multi-Surface Spray 500ml',
    slug: 'flash-multi-surface-500ml',
    shortDescription: 'Cleans and shines multiple surfaces.',
    brand: 'Flash',
    basePrice: 220,
    images: gallery('Flash'),
    tags: ['household', 'cleaning'],
    categorySlugs: ['household'],
    variants: [],
  },
  {
    sku: 'COLG-TP-100',
    name: 'Colgate Total Toothpaste 100ml',
    slug: 'colgate-total-100ml',
    shortDescription: 'Complete 12-hour protection.',
    brand: 'Colgate',
    basePrice: 250,
    images: gallery('Colgate'),
    tags: ['health', 'dental'],
    categorySlugs: ['health-beauty'],
    variants: [],
  },
  {
    sku: 'DOVE-SOAP-2PK',
    name: 'Dove Original Beauty Bar 2x90g',
    slug: 'dove-beauty-bar-2pk',
    shortDescription: 'Moisturising beauty bar for soft skin.',
    brand: 'Dove',
    basePrice: 230,
    images: gallery('Dove'),
    tags: ['beauty', 'soap'],
    categorySlugs: ['health-beauty'],
    variants: [],
  },
  {
    sku: 'LYNX-AFR-150',
    name: 'Lynx Africa Body Spray 150ml',
    slug: 'lynx-africa-150ml',
    shortDescription: 'The iconic fragrance.',
    brand: 'Lynx',
    basePrice: 320,
    images: gallery('Lynx'),
    tags: ['beauty', 'deodorant'],
    categorySlugs: ['health-beauty'],
    variants: [],
  },
  {
    sku: 'TSHIRT-STORE',
    name: 'Store Logo T-Shirt',
    slug: 'store-logo-t-shirt',
    shortDescription: 'Soft cotton t-shirt with store logo.',
    brand: 'Own Brand',
    basePrice: 999,
    images: gallery('T-Shirt'),
    tags: ['merch', 'clothing'],
    categorySlugs: ['household'],
    variants: [
      { suffix: 'BLK-S', name: 'Store Logo T-Shirt — Black S', attributes: { colour: 'Black', size: 'S' }, isDefault: true },
      { suffix: 'BLK-M', name: 'Store Logo T-Shirt — Black M', attributes: { colour: 'Black', size: 'M' } },
      { suffix: 'BLK-L', name: 'Store Logo T-Shirt — Black L', attributes: { colour: 'Black', size: 'L' } },
      { suffix: 'WHT-M', name: 'Store Logo T-Shirt — White M', attributes: { colour: 'White', size: 'M' }, priceDelta: 0 },
      { suffix: 'WHT-L', name: 'Store Logo T-Shirt — White L', attributes: { colour: 'White', size: 'L' } },
    ],
  },
  {
    sku: 'LUCOZ-ORIG-380',
    name: 'Lucozade Energy Original 380ml',
    slug: 'lucozade-energy-original-380ml',
    shortDescription: 'Glucose energy drink, 380ml bottle.',
    brand: 'Lucozade',
    basePrice: 125,
    images: gallery('Lucozade'),
    tags: ['energy'],
    categorySlugs: ['energy-drinks', 'soft-drinks'],
    variants: [],
  },
];

export const CUSTOMERS = [
  /** Synthetic customer for in-store POS / cash walk-in sales (orders require customerId). */
  {
    email: 'walk-in@pos.local',
    firstName: 'Walk-in',
    lastName: 'Customer',
    phone: undefined,
    marketingOptIn: false,
    address: undefined,
  },
  { email: 'alice@example.dev', firstName: 'Alice', lastName: 'Anderson', phone: '+44 7700 900001', marketingOptIn: true, address: { line1: '10 Rose Street', city: 'Glasgow', postcode: 'G1 5AA' } },
  { email: 'bob@example.dev', firstName: 'Bob', lastName: 'Brown', phone: '+44 7700 900002', marketingOptIn: false, address: { line1: '22 Leith Walk', city: 'Edinburgh', postcode: 'EH6 8AA' } },
  { email: 'carol@example.dev', firstName: 'Carol', lastName: 'Campbell', phone: '+44 7700 900003', marketingOptIn: true, address: { line1: '3 Mill Lane', city: 'Paisley', postcode: 'PA1 1XX' } },
  { email: 'dan@example.dev', firstName: 'Dan', lastName: 'Davies', phone: '+44 7700 900004', marketingOptIn: false, address: { line1: '77 Deansgate', city: 'Manchester', postcode: 'M3 2BW' } },
  { email: 'erin@example.dev', firstName: 'Erin', lastName: 'Evans', phone: '+44 7700 900005', marketingOptIn: true, address: { line1: '5 Baker Street', city: 'London', postcode: 'NW1 6XE' } },
  { email: 'frank@example.dev', firstName: 'Frank', lastName: 'Fraser', phone: '+44 7700 900006', marketingOptIn: false, address: { line1: '14 Hope Street', city: 'Glasgow', postcode: 'G2 6AB' } },
  { email: 'grace@example.dev', firstName: 'Grace', lastName: 'Graham', phone: '+44 7700 900007', marketingOptIn: true, address: { line1: '9 Royal Mile', city: 'Edinburgh', postcode: 'EH1 1RE' } },
  { email: 'henry@example.dev', firstName: 'Henry', lastName: 'Hughes', phone: '+44 7700 900008', marketingOptIn: false, address: { line1: '31 Curry Mile', city: 'Manchester', postcode: 'M14 5LN' } },
];
