import type {
  DeliveryDefaultsInput,
  SocialLinksInput,
  StoreDetailsInput,
} from '@repo/validation';

export const SETTING_KEYS = {
  store: 'store.details',
  social: 'social.links',
  delivery: 'delivery.defaults',
} as const;

export const DEFAULT_STORE_DETAILS: StoreDetailsInput = {
  storeName: 'Neighbourhood Market',
  legalName: 'Neighbourhood Market Ltd',
  supportEmail: 'support@neighbourhood.market',
  supportPhone: '+44 20 7946 0000',
  addressLine1: '1 Market Square',
  addressLine2: '',
  city: 'London',
  postcode: 'EC1A 1BB',
  country: 'GB',
  website: '',
  logoUrl: '',
  timezone: 'Europe/London',
  currency: 'GBP',
  vatNumber: '',
  companyNumber: '',
  tagline: 'Your local shop, online',
};

export const DEFAULT_SOCIAL_LINKS: SocialLinksInput = {
  facebook: '',
  instagram: '',
  x: '',
  tiktok: '',
  youtube: '',
  linkedin: '',
};

export const DEFAULT_DELIVERY: DeliveryDefaultsInput = {
  defaultDeliveryFee: 399,
  defaultFreeDeliveryThreshold: 2500,
  deliveryNotes: 'Delivery fees are set per branch. Free delivery applies when the basket meets the branch threshold.',
  estimatedDeliveryHours: '2–4 hours (same day where available)',
  minOrderForDelivery: null,
};

export const DEFAULT_PLUGINS = [
  {
    code: 'whatsapp_chat',
    name: 'WhatsApp chat',
    description: 'Floating WhatsApp button on the storefront for customer support.',
    category: 'chat',
    provider: 'whatsapp',
    sortOrder: 1,
    isEnabled: false,
    config: {
      phoneE164: '+447700900123',
      prefilledMessage: 'Hi, I need help with my order',
      buttonLabel: 'Chat on WhatsApp',
    },
  },
  {
    code: 'facebook_chat',
    name: 'Facebook / Messenger',
    description: 'Link customers to your Facebook Page or Messenger.',
    category: 'social',
    provider: 'facebook',
    sortOrder: 2,
    isEnabled: false,
    config: {
      pageUrl: 'https://www.facebook.com/',
      messengerUrl: '',
      showFloatingButton: true,
    },
  },
  {
    code: 'dpd_uk',
    name: 'DPD UK',
    description: 'UK parcel delivery partner (DPD). Configure merchant/account refs for labelling.',
    category: 'delivery',
    provider: 'dpd',
    sortOrder: 10,
    isEnabled: false,
    config: { accountNumber: '', trackingBaseUrl: 'https://www.dpd.co.uk/tracking', notes: '' },
  },
  {
    code: 'evri_uk',
    name: 'Evri (Hermes)',
    description: 'UK nationwide parcel network formerly Hermes.',
    category: 'delivery',
    provider: 'evri',
    sortOrder: 11,
    isEnabled: false,
    config: { clientId: '', trackingBaseUrl: 'https://www.evri.com/track', notes: '' },
  },
  {
    code: 'royal_mail',
    name: 'Royal Mail',
    description: 'Royal Mail Tracked / Special Delivery for UK online orders.',
    category: 'delivery',
    provider: 'royal_mail',
    sortOrder: 12,
    isEnabled: false,
    config: { accountNumber: '', trackingBaseUrl: 'https://www.royalmail.com/track-your-item', notes: '' },
  },
  {
    code: 'yodel_uk',
    name: 'Yodel',
    description: 'Yodel UK parcel delivery partner.',
    category: 'delivery',
    provider: 'yodel',
    sortOrder: 13,
    isEnabled: false,
    config: { accountNumber: '', trackingBaseUrl: 'https://www.yodel.co.uk/track', notes: '' },
  },
  {
    code: 'stuart_uk',
    name: 'Stuart',
    description: 'On-demand urban courier for same-day local delivery in UK cities.',
    category: 'delivery',
    provider: 'stuart',
    sortOrder: 14,
    isEnabled: false,
    config: { clientId: '', city: 'london', notes: 'API keys stay in environment variables (STUART_*).' },
  },
  {
    code: 'gophr_uk',
    name: 'Gophr',
    description: 'London / UK same-day courier API for grocery-style fulfilment.',
    category: 'delivery',
    provider: 'gophr',
    sortOrder: 15,
    isEnabled: false,
    config: { apiKeyHint: 'Set GOPHR_API_KEY in environment', notes: '' },
  },
  {
    code: 'ups_uk',
    name: 'UPS UK',
    description: 'UPS domestic and international shipping from UK branches.',
    category: 'delivery',
    provider: 'ups',
    sortOrder: 16,
    isEnabled: false,
    config: { accountNumber: '', trackingBaseUrl: 'https://www.ups.com/track', notes: '' },
  },
  {
    code: 'dhl_express_uk',
    name: 'DHL Express',
    description: 'DHL Express for next-day / international parcels.',
    category: 'delivery',
    provider: 'dhl',
    sortOrder: 17,
    isEnabled: false,
    config: { accountNumber: '', trackingBaseUrl: 'https://www.dhl.com/gb-en/home/tracking.html', notes: '' },
  },
] as const;
