import type {
  DeliveryDefaultsInput,
  SocialLinksInput,
  StoreDetailsInput,
} from '@repo/validation';

export const SETTING_KEYS = {
  store: 'store.details',
  social: 'social.links',
  delivery: 'delivery.defaults',
} as const;

export const DEFAULT_STORE_DETAILS: StoreDetailsInput = {
  storeName: 'Neighbourhood Market',
  legalName: 'Neighbourhood Market Ltd',
  supportEmail: 'support@neighbourhood.market',
  supportPhone: '+44 20 7946 0000',
  addressLine1: '1 Market Square',
  addressLine2: '',
  city: 'London',
  postcode: 'EC1A 1BB',
  country: 'GB',
  website: '',
  logoUrl: '',
  timezone: 'Europe/London',
  currency: 'GBP',
  vatNumber: '',
  companyNumber: '',
  tagline: 'Your local shop, online',
};

export const DEFAULT_SOCIAL_LINKS: SocialLinksInput = {
  facebook: '',
  instagram: '',
  x: '',
  tiktok: '',
  youtube: '',
  linkedin: '',
};

export const DEFAULT_DELIVERY: DeliveryDefaultsInput = {
  defaultDeliveryFee: 399,
  defaultFreeDeliveryThreshold: 2500,
  deliveryNotes: 'Delivery fees are set per branch. Free delivery applies when the basket meets the branch threshold.',
  estimatedDeliveryHours: '2–4 hours (same day where available)',
  minOrderForDelivery: null,
};

export const DEFAULT_PLUGINS = [
  {
    code: 'whatsapp_chat',
    name: 'WhatsApp chat',
    description: 'Floating WhatsApp button on the storefront for customer support.',
    category: 'chat',
    provider: 'whatsapp',
    sortOrder: 1,
    isEnabled: false,
    config: {
      phoneE164: '+447700900123',
      prefilledMessage: 'Hi, I need help with my order',
      buttonLabel: 'Chat on WhatsApp',
    },
  },
  {
    code: 'facebook_chat',
    name: 'Facebook / Messenger',
    description: 'Link customers to your Facebook Page or Messenger.',
    category: 'social',
    provider: 'facebook',
    sortOrder: 2,
    isEnabled: false,
    config: {
      pageUrl: 'https://www.facebook.com/',
      messengerUrl: '',
      showFloatingButton: true,
    },
  },
  {
    code: 'dpd_uk',
    name: 'DPD UK',
    description: 'UK parcel delivery partner (DPD). Configure merchant/account refs for labelling.',
    category: 'delivery',
    provider: 'dpd',
    sortOrder: 10,
    isEnabled: false,
    config: { accountNumber: '', trackingBaseUrl: 'https://www.dpd.co.uk/tracking', notes: '' },
  },
  {
    code: 'evri_uk',
    name: 'Evri (Hermes)',
    description: 'UK nationwide parcel network formerly Hermes.',
    category: 'delivery',
    provider: 'evri',
    sortOrder: 11,
    isEnabled: false,
    config: { clientId: '', trackingBaseUrl: 'https://www.evri.com/track', notes: '' },
  },
  {
    code: 'royal_mail',
    name: 'Royal Mail',
    description: 'Royal Mail Tracked / Special Delivery for UK online orders.',
    category: 'delivery',
    provider: 'royal_mail',
    sortOrder: 12,
    isEnabled: false,
    config: { accountNumber: '', trackingBaseUrl: 'https://www.royalmail.com/track-your-item', notes: '' },
  },
  {
    code: 'yodel_uk',
    name: 'Yodel',
    description: 'Yodel UK parcel delivery partner.',
    category: 'delivery',
    provider: 'yodel',
    sortOrder: 13,
    isEnabled: false,
    config: { accountNumber: '', trackingBaseUrl: 'https://www.yodel.co.uk/track', notes: '' },
  },
  {
    code: 'stuart_uk',
    name: 'Stuart',
    description: 'On-demand urban courier for same-day local delivery in UK cities.',
    category: 'delivery',
    provider: 'stuart',
    sortOrder: 14,
    isEnabled: false,
    config: { clientId: '', city: 'london', notes: 'API keys stay in environment variables (STUART_*).' },
  },
  {
    code: 'gophr_uk',
    name: 'Gophr',
    description: 'London / UK same-day courier API for grocery-style fulfilment.',
    category: 'delivery',
    provider: 'gophr',
    sortOrder: 15,
    isEnabled: false,
    config: { apiKeyHint: 'Set GOPHR_API_KEY in environment', notes: '' },
  },
  {
    code: 'ups_uk',
    name: 'UPS UK',
    description: 'UPS domestic and international shipping from UK branches.',
    category: 'delivery',
    provider: 'ups',
    sortOrder: 16,
    isEnabled: false,
    config: { accountNumber: '', trackingBaseUrl: 'https://www.ups.com/track', notes: '' },
  },
  {
    code: 'dhl_express_uk',
    name: 'DHL Express',
    description: 'DHL Express for next-day / international parcels.',
    category: 'delivery',
    provider: 'dhl',
    sortOrder: 17,
    isEnabled: false,
    config: { accountNumber: '', trackingBaseUrl: 'https://www.dhl.com/gb-en/home/tracking.html', notes: '' },
  },
  {
    code: 'uber_eats',
    name: 'Uber Eats',
    description: 'Connect your stores to Uber Eats for marketplace orders and menu sync.',
    category: 'marketplace',
    provider: 'uber_eats',
    sortOrder: 20,
    isEnabled: false,
    config: {
      storeId: '',
      merchantId: '',
      sandbox: true,
      webhookPath: '/api/v1/webhooks/uber-eats',
      docsUrl: 'https://developer.uber.com/docs/eats',
      envVars: ['UBER_EATS_CLIENT_ID', 'UBER_EATS_CLIENT_SECRET', 'UBER_EATS_WEBHOOK_SECRET'],
      setupSteps: [
        'Create an Uber Eats developer app and note Client ID / Secret',
        'Set UBER_EATS_* environment variables and restart the API',
        'Enter your Uber Eats store / merchant IDs below',
        'Register the webhook URL in the Uber developer console',
        'Enable this app and map branches to Uber store IDs',
      ],
    },
  },
  {
    code: 'uber_direct',
    name: 'Uber Direct',
    description: 'On-demand courier delivery via Uber Direct for your own online orders.',
    category: 'marketplace',
    provider: 'uber',
    sortOrder: 21,
    isEnabled: false,
    config: {
      customerId: '',
      sandbox: true,
      webhookPath: '/api/v1/webhooks/uber-direct',
      docsUrl: 'https://developer.uber.com/docs/direct',
      envVars: ['UBER_DIRECT_CUSTOMER_ID', 'UBER_DIRECT_CLIENT_ID', 'UBER_DIRECT_CLIENT_SECRET'],
      setupSteps: [
        'Apply for Uber Direct and create API credentials',
        'Set UBER_DIRECT_* environment variables',
        'Enter Customer ID below and enable the app',
        'Test a quote + delivery create in sandbox before going live',
      ],
    },
  },
  {
    code: 'deliveroo',
    name: 'Deliveroo',
    description: 'Partner with Deliveroo for marketplace orders across UK cities.',
    category: 'marketplace',
    provider: 'deliveroo',
    sortOrder: 22,
    isEnabled: false,
    config: {
      brandId: '',
      siteId: '',
      sandbox: true,
      webhookPath: '/api/v1/webhooks/deliveroo',
      docsUrl: 'https://developers.deliveroo.com/',
      envVars: ['DELIVEROO_API_KEY', 'DELIVEROO_WEBHOOK_SECRET'],
      setupSteps: [
        'Request Deliveroo partner / developer access',
        'Set DELIVEROO_API_KEY and webhook secret in environment',
        'Add brand and site IDs for each branch mapping',
        'Enable the app and verify menu sync in sandbox',
      ],
    },
  },
  {
    code: 'just_eat',
    name: 'Just Eat',
    description: 'Just Eat Takeaway.com restaurant / grocery marketplace integration.',
    category: 'marketplace',
    provider: 'just_eat',
    sortOrder: 23,
    isEnabled: false,
    config: {
      restaurantId: '',
      partnerId: '',
      sandbox: true,
      webhookPath: '/api/v1/webhooks/just-eat',
      docsUrl: 'https://developer.just-eat.com/',
      envVars: ['JUST_EAT_API_KEY', 'JUST_EAT_WEBHOOK_SECRET'],
      setupSteps: [
        'Register as a Just Eat partner and create API credentials',
        'Set JUST_EAT_* environment variables',
        'Enter restaurant / partner IDs below',
        'Point webhooks at your API and enable the app',
      ],
    },
  },
  {
    code: 'doordash_drive',
    name: 'DoorDash Drive',
    description: 'DoorDash Drive white-label delivery for your own checkout orders.',
    category: 'marketplace',
    provider: 'doordash',
    sortOrder: 24,
    isEnabled: false,
    config: {
      developerId: '',
      externalStoreId: '',
      sandbox: true,
      webhookPath: '/api/v1/webhooks/doordash',
      docsUrl: 'https://developer.doordash.com/en-US/docs/drive/',
      envVars: ['DOORDASH_DEVELOPER_ID', 'DOORDASH_KEY_ID', 'DOORDASH_SIGNING_SECRET'],
      setupSteps: [
        'Create a DoorDash Drive developer account',
        'Set DOORDASH_* environment variables (JWT signing)',
        'Map external store IDs to branches',
        'Enable and run a sandbox delivery quote test',
      ],
    },
  },
  {
    code: 'getir',
    name: 'Getir',
    description: 'Getir grocery / quick commerce marketplace partnership.',
    category: 'marketplace',
    provider: 'getir',
    sortOrder: 25,
    isEnabled: false,
    config: {
      merchantId: '',
      warehouseId: '',
      sandbox: true,
      webhookPath: '/api/v1/webhooks/getir',
      docsUrl: 'https://developers.getir.com/',
      envVars: ['GETIR_API_KEY', 'GETIR_WEBHOOK_SECRET'],
      setupSteps: [
        'Request Getir partner API access',
        'Set GETIR_* secrets in environment',
        'Enter merchant / warehouse IDs',
        'Enable the app after webhook verification',
      ],
    },
  },
] as const;
